import { lazy, Suspense, useEffect } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "@/components/quickbridge/icons";
import { AppHeader } from "@/components/quickbridge/Wordmark";
import { SessionSkeleton } from "@/components/quickbridge/SessionSkeleton";
import { supabase } from "@/integrations/supabase/client";

const Session = lazy(() =>
  import("@/components/quickbridge/Session").then((m) => ({ default: m.Session }))
);

// Session IDs are lowercase alphanumeric, 6-32 chars (generated by generateSessionId()).
// Validate before mounting the signaling stack so garbage URLs fail fast with
// a clear recovery path instead of a 30-second "Host not found" dead-end.
const SESSION_ID_RE = /^[a-z0-9]{6,32}$/i;

export const Route = createFileRoute("/s/$id")({
  component: GuestSession,
  head: () => ({
    meta: [
      { title: "Joining session - QuickBridge" },
      { name: "description", content: "Connecting to a QuickBridge pairing session." },
      { name: "robots", content: "noindex, nofollow" },
    ],
  }),
});

function GuestSession() {
  const { id } = Route.useParams();

  useEffect(() => {
    // Fire-and-forget: count this QR scan. Errors are intentionally swallowed
    // so a missing table or network failure never surfaces to the guest.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (supabase as any).rpc("increment_qr_scan").then(() => {});
  }, []);

  if (!SESSION_ID_RE.test(id)) {
    return (
      <div className="relative min-h-screen overflow-hidden">
        <AppHeader
          maxWidthClass="max-w-6xl"
          rightSlot={
            <Link
              to="/"
              className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card/60 px-2.5 py-1 text-[11px] font-medium text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="h-3 w-3" />
              Home
            </Link>
          }
        />
        <main className="relative mx-auto max-w-md px-4 pb-24 pt-16 sm:px-6 text-center space-y-3">
          <p className="text-[15px] font-semibold text-foreground">Invalid session link</p>
          <p className="text-[13px] text-muted-foreground">
            This link doesn't look right. Ask the host to share a fresh QR code or PIN.
          </p>
          <Link
            to="/"
            className="inline-block text-[13px] font-medium text-primary hover:underline"
          >
            Go home
          </Link>
        </main>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen overflow-hidden">
      <AppHeader
        maxWidthClass="max-w-6xl"
        rightSlot={
          <Link
            to="/"
            className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card/60 px-2.5 py-1 text-[11px] font-medium text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="h-3 w-3" />
            Home
          </Link>
        }
      />
      <main className="relative mx-auto max-w-6xl px-4 pb-24 pt-8 sm:px-6">
        {/* key={id}: see session.$id.tsx for the full explanation. Forces
            a full remount of Session whenever the session ID changes so
            no session-scoped state can leak between sessions. */}
        <Suspense key={id} fallback={<SessionSkeleton />}>
          <Session sessionId={id} isInitiator={false} />
        </Suspense>
      </main>
    </div>
  );
}
