import { lazy, Suspense } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "@/components/quickbridge/icons";
import { AppHeader } from "@/components/quickbridge/Wordmark";
import { SessionSkeleton } from "@/components/quickbridge/SessionSkeleton";

const Session = lazy(() =>
  import("@/components/quickbridge/Session").then((m) => ({ default: m.Session }))
);

// Session IDs are lowercase alphanumeric, 6-32 chars (generated by generateSessionId()).
// Validate before mounting the signaling stack so garbage URLs fail fast with
// a clear recovery path instead of an indefinite "Waiting for the other device" state.
const SESSION_ID_RE = /^[a-z0-9]{6,32}$/i;

export const Route = createFileRoute("/session/$id")({
  component: HostSession,
  head: () => ({
    meta: [
      { title: "Session - QuickBridge" },
      { name: "description", content: "Active QuickBridge session." },
      { name: "robots", content: "noindex, nofollow" },
    ],
  }),
});

function HostSession() {
  const { id } = Route.useParams();

  if (!SESSION_ID_RE.test(id)) {
    return (
      <div className="relative min-h-screen overflow-hidden">
        <AppHeader
          maxWidthClass="max-w-6xl"
          rightSlot={
            <Link
              to="/"
              className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card/60 px-2.5 py-1 text-[11px] font-medium text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="h-3 w-3" />
              Home
            </Link>
          }
        />
        <main className="relative mx-auto max-w-md px-4 pb-24 pt-16 sm:px-6 text-center space-y-3">
          <p className="text-[15px] font-semibold text-foreground">Invalid session link</p>
          <p className="text-[13px] text-muted-foreground">
            This link doesn't look right. Start a fresh bridge from the home screen.
          </p>
          <Link
            to="/"
            className="inline-block text-[13px] font-medium text-primary hover:underline"
          >
            Go home
          </Link>
        </main>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen overflow-hidden">
      <AppHeader
        maxWidthClass="max-w-6xl"
        rightSlot={
          <Link
            to="/"
            className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card/60 px-2.5 py-1 text-[11px] font-medium text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="h-3 w-3" />
            New session
          </Link>
        }
      />
      <main className="relative mx-auto max-w-6xl px-4 pb-24 pt-8 sm:px-6">
        {/* key={id} forces a full unmount + remount of Session (and all its
            hooks) if the session ID ever changes while this route stays
            mounted. This resets all session-scoped React state (messages,
            incomingFiles, outgoingFiles, sasCode, quality, etc.) so stale
            transfer rows from the previous session can never flash into the
            new one. */}
        <Suspense key={id} fallback={<SessionSkeleton />}>
          <Session sessionId={id} isInitiator={true} />
        </Suspense>
      </main>
    </div>
  );
}
