/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyQuickbridgeRouteImport } from './routes/why-quickbridge'
import { Route as VideoRouteImport } from './routes/video'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AirdropAlternativeRouteImport } from './routes/airdrop-alternative'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as HowToShareFilesSameWifiRouteImport } from './routes/how-to.share-files-same-wifi'
import { Route as HowToSendPhotosPhoneToPcRouteImport } from './routes/how-to.send-photos-phone-to-pc'
import { Route as HowToSendPdfPhoneToPcRouteImport } from './routes/how-to.send-pdf-phone-to-pc'
import { Route as HowToSendLargeFilesPhoneToPcRouteImport } from './routes/how-to.send-large-files-phone-to-pc'
import { Route as HowToSendFilesWithoutWhatsappRouteImport } from './routes/how-to.send-files-without-whatsapp'
import { Route as HowToSendFilesWindowsToIphoneRouteImport } from './routes/how-to.send-files-windows-to-iphone'
import { Route as HowToSendFilesWindowsToAndroidRouteImport } from './routes/how-to.send-files-windows-to-android'
import { Route as HowToSendFilesPhoneToPcFreeRouteImport } from './routes/how-to.send-files-phone-to-pc-free'
import { Route as HowToSendFilesIphoneToWindowsRouteImport } from './routes/how-to.send-files-iphone-to-windows'
import { Route as HowToSendFilesIphoneToMacRouteImport } from './routes/how-to.send-files-iphone-to-mac'
import { Route as HowToSendFilesAndroidToWindowsRouteImport } from './routes/how-to.send-files-android-to-windows'
import { Route as HowToSendFilesAndroidToMacRouteImport } from './routes/how-to.send-files-android-to-mac'
import { Route as CompareQuickbridgeVsWormholeRouteImport } from './routes/compare.quickbridge-vs-wormhole'
import { Route as CompareQuickbridgeVsWetransferRouteImport } from './routes/compare.quickbridge-vs-wetransfer'
import { Route as CompareQuickbridgeVsSnapdropRouteImport } from './routes/compare.quickbridge-vs-snapdrop'
import { Route as CompareQuickbridgeVsPairdropRouteImport } from './routes/compare.quickbridge-vs-pairdrop'
import { Route as CompareQuickbridgeVsAirdropRouteImport } from './routes/compare.quickbridge-vs-airdrop'

const WhyQuickbridgeRoute = WhyQuickbridgeRouteImport.update({
  id: '/why-quickbridge',
  path: '/why-quickbridge',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AirdropAlternativeRoute = AirdropAlternativeRouteImport.update({
  id: '/airdrop-alternative',
  path: '/airdrop-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToShareFilesSameWifiRoute = HowToShareFilesSameWifiRouteImport.update({
  id: '/how-to/share-files-same-wifi',
  path: '/how-to/share-files-same-wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToSendPhotosPhoneToPcRoute =
  HowToSendPhotosPhoneToPcRouteImport.update({
    id: '/how-to/send-photos-phone-to-pc',
    path: '/how-to/send-photos-phone-to-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendPdfPhoneToPcRoute = HowToSendPdfPhoneToPcRouteImport.update({
  id: '/how-to/send-pdf-phone-to-pc',
  path: '/how-to/send-pdf-phone-to-pc',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToSendLargeFilesPhoneToPcRoute =
  HowToSendLargeFilesPhoneToPcRouteImport.update({
    id: '/how-to/send-large-files-phone-to-pc',
    path: '/how-to/send-large-files-phone-to-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesWithoutWhatsappRoute =
  HowToSendFilesWithoutWhatsappRouteImport.update({
    id: '/how-to/send-files-without-whatsapp',
    path: '/how-to/send-files-without-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesWindowsToIphoneRoute =
  HowToSendFilesWindowsToIphoneRouteImport.update({
    id: '/how-to/send-files-windows-to-iphone',
    path: '/how-to/send-files-windows-to-iphone',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesWindowsToAndroidRoute =
  HowToSendFilesWindowsToAndroidRouteImport.update({
    id: '/how-to/send-files-windows-to-android',
    path: '/how-to/send-files-windows-to-android',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesPhoneToPcFreeRoute =
  HowToSendFilesPhoneToPcFreeRouteImport.update({
    id: '/how-to/send-files-phone-to-pc-free',
    path: '/how-to/send-files-phone-to-pc-free',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesIphoneToWindowsRoute =
  HowToSendFilesIphoneToWindowsRouteImport.update({
    id: '/how-to/send-files-iphone-to-windows',
    path: '/how-to/send-files-iphone-to-windows',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesIphoneToMacRoute =
  HowToSendFilesIphoneToMacRouteImport.update({
    id: '/how-to/send-files-iphone-to-mac',
    path: '/how-to/send-files-iphone-to-mac',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesAndroidToWindowsRoute =
  HowToSendFilesAndroidToWindowsRouteImport.update({
    id: '/how-to/send-files-android-to-windows',
    path: '/how-to/send-files-android-to-windows',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSendFilesAndroidToMacRoute =
  HowToSendFilesAndroidToMacRouteImport.update({
    id: '/how-to/send-files-android-to-mac',
    path: '/how-to/send-files-android-to-mac',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsWormholeRoute =
  CompareQuickbridgeVsWormholeRouteImport.update({
    id: '/compare/quickbridge-vs-wormhole',
    path: '/compare/quickbridge-vs-wormhole',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsWetransferRoute =
  CompareQuickbridgeVsWetransferRouteImport.update({
    id: '/compare/quickbridge-vs-wetransfer',
    path: '/compare/quickbridge-vs-wetransfer',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsSnapdropRoute =
  CompareQuickbridgeVsSnapdropRouteImport.update({
    id: '/compare/quickbridge-vs-snapdrop',
    path: '/compare/quickbridge-vs-snapdrop',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsPairdropRoute =
  CompareQuickbridgeVsPairdropRouteImport.update({
    id: '/compare/quickbridge-vs-pairdrop',
    path: '/compare/quickbridge-vs-pairdrop',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsAirdropRoute =
  CompareQuickbridgeVsAirdropRouteImport.update({
    id: '/compare/quickbridge-vs-airdrop',
    path: '/compare/quickbridge-vs-airdrop',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airdrop-alternative': typeof AirdropAlternativeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/video': typeof VideoRoute
  '/why-quickbridge': typeof WhyQuickbridgeRoute
  '/compare/quickbridge-vs-airdrop': typeof CompareQuickbridgeVsAirdropRoute
  '/compare/quickbridge-vs-pairdrop': typeof CompareQuickbridgeVsPairdropRoute
  '/compare/quickbridge-vs-snapdrop': typeof CompareQuickbridgeVsSnapdropRoute
  '/compare/quickbridge-vs-wetransfer': typeof CompareQuickbridgeVsWetransferRoute
  '/compare/quickbridge-vs-wormhole': typeof CompareQuickbridgeVsWormholeRoute
  '/how-to/send-files-android-to-mac': typeof HowToSendFilesAndroidToMacRoute
  '/how-to/send-files-android-to-windows': typeof HowToSendFilesAndroidToWindowsRoute
  '/how-to/send-files-iphone-to-mac': typeof HowToSendFilesIphoneToMacRoute
  '/how-to/send-files-iphone-to-windows': typeof HowToSendFilesIphoneToWindowsRoute
  '/how-to/send-files-phone-to-pc-free': typeof HowToSendFilesPhoneToPcFreeRoute
  '/how-to/send-files-windows-to-android': typeof HowToSendFilesWindowsToAndroidRoute
  '/how-to/send-files-windows-to-iphone': typeof HowToSendFilesWindowsToIphoneRoute
  '/how-to/send-files-without-whatsapp': typeof HowToSendFilesWithoutWhatsappRoute
  '/how-to/send-large-files-phone-to-pc': typeof HowToSendLargeFilesPhoneToPcRoute
  '/how-to/send-pdf-phone-to-pc': typeof HowToSendPdfPhoneToPcRoute
  '/how-to/send-photos-phone-to-pc': typeof HowToSendPhotosPhoneToPcRoute
  '/how-to/share-files-same-wifi': typeof HowToShareFilesSameWifiRoute
  '/s/$id': typeof SIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airdrop-alternative': typeof AirdropAlternativeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/video': typeof VideoRoute
  '/why-quickbridge': typeof WhyQuickbridgeRoute
  '/compare/quickbridge-vs-airdrop': typeof CompareQuickbridgeVsAirdropRoute
  '/compare/quickbridge-vs-pairdrop': typeof CompareQuickbridgeVsPairdropRoute
  '/compare/quickbridge-vs-snapdrop': typeof CompareQuickbridgeVsSnapdropRoute
  '/compare/quickbridge-vs-wetransfer': typeof CompareQuickbridgeVsWetransferRoute
  '/compare/quickbridge-vs-wormhole': typeof CompareQuickbridgeVsWormholeRoute
  '/how-to/send-files-android-to-mac': typeof HowToSendFilesAndroidToMacRoute
  '/how-to/send-files-android-to-windows': typeof HowToSendFilesAndroidToWindowsRoute
  '/how-to/send-files-iphone-to-mac': typeof HowToSendFilesIphoneToMacRoute
  '/how-to/send-files-iphone-to-windows': typeof HowToSendFilesIphoneToWindowsRoute
  '/how-to/send-files-phone-to-pc-free': typeof HowToSendFilesPhoneToPcFreeRoute
  '/how-to/send-files-windows-to-android': typeof HowToSendFilesWindowsToAndroidRoute
  '/how-to/send-files-windows-to-iphone': typeof HowToSendFilesWindowsToIphoneRoute
  '/how-to/send-files-without-whatsapp': typeof HowToSendFilesWithoutWhatsappRoute
  '/how-to/send-large-files-phone-to-pc': typeof HowToSendLargeFilesPhoneToPcRoute
  '/how-to/send-pdf-phone-to-pc': typeof HowToSendPdfPhoneToPcRoute
  '/how-to/send-photos-phone-to-pc': typeof HowToSendPhotosPhoneToPcRoute
  '/how-to/share-files-same-wifi': typeof HowToShareFilesSameWifiRoute
  '/s/$id': typeof SIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airdrop-alternative': typeof AirdropAlternativeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/video': typeof VideoRoute
  '/why-quickbridge': typeof WhyQuickbridgeRoute
  '/compare/quickbridge-vs-airdrop': typeof CompareQuickbridgeVsAirdropRoute
  '/compare/quickbridge-vs-pairdrop': typeof CompareQuickbridgeVsPairdropRoute
  '/compare/quickbridge-vs-snapdrop': typeof CompareQuickbridgeVsSnapdropRoute
  '/compare/quickbridge-vs-wetransfer': typeof CompareQuickbridgeVsWetransferRoute
  '/compare/quickbridge-vs-wormhole': typeof CompareQuickbridgeVsWormholeRoute
  '/how-to/send-files-android-to-mac': typeof HowToSendFilesAndroidToMacRoute
  '/how-to/send-files-android-to-windows': typeof HowToSendFilesAndroidToWindowsRoute
  '/how-to/send-files-iphone-to-mac': typeof HowToSendFilesIphoneToMacRoute
  '/how-to/send-files-iphone-to-windows': typeof HowToSendFilesIphoneToWindowsRoute
  '/how-to/send-files-phone-to-pc-free': typeof HowToSendFilesPhoneToPcFreeRoute
  '/how-to/send-files-windows-to-android': typeof HowToSendFilesWindowsToAndroidRoute
  '/how-to/send-files-windows-to-iphone': typeof HowToSendFilesWindowsToIphoneRoute
  '/how-to/send-files-without-whatsapp': typeof HowToSendFilesWithoutWhatsappRoute
  '/how-to/send-large-files-phone-to-pc': typeof HowToSendLargeFilesPhoneToPcRoute
  '/how-to/send-pdf-phone-to-pc': typeof HowToSendPdfPhoneToPcRoute
  '/how-to/send-photos-phone-to-pc': typeof HowToSendPhotosPhoneToPcRoute
  '/how-to/share-files-same-wifi': typeof HowToShareFilesSameWifiRoute
  '/s/$id': typeof SIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airdrop-alternative'
    | '/help'
    | '/join'
    | '/privacy'
    | '/video'
    | '/why-quickbridge'
    | '/compare/quickbridge-vs-airdrop'
    | '/compare/quickbridge-vs-pairdrop'
    | '/compare/quickbridge-vs-snapdrop'
    | '/compare/quickbridge-vs-wetransfer'
    | '/compare/quickbridge-vs-wormhole'
    | '/how-to/send-files-android-to-mac'
    | '/how-to/send-files-android-to-windows'
    | '/how-to/send-files-iphone-to-mac'
    | '/how-to/send-files-iphone-to-windows'
    | '/how-to/send-files-phone-to-pc-free'
    | '/how-to/send-files-windows-to-android'
    | '/how-to/send-files-windows-to-iphone'
    | '/how-to/send-files-without-whatsapp'
    | '/how-to/send-large-files-phone-to-pc'
    | '/how-to/send-pdf-phone-to-pc'
    | '/how-to/send-photos-phone-to-pc'
    | '/how-to/share-files-same-wifi'
    | '/s/$id'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airdrop-alternative'
    | '/help'
    | '/join'
    | '/privacy'
    | '/video'
    | '/why-quickbridge'
    | '/compare/quickbridge-vs-airdrop'
    | '/compare/quickbridge-vs-pairdrop'
    | '/compare/quickbridge-vs-snapdrop'
    | '/compare/quickbridge-vs-wetransfer'
    | '/compare/quickbridge-vs-wormhole'
    | '/how-to/send-files-android-to-mac'
    | '/how-to/send-files-android-to-windows'
    | '/how-to/send-files-iphone-to-mac'
    | '/how-to/send-files-iphone-to-windows'
    | '/how-to/send-files-phone-to-pc-free'
    | '/how-to/send-files-windows-to-android'
    | '/how-to/send-files-windows-to-iphone'
    | '/how-to/send-files-without-whatsapp'
    | '/how-to/send-large-files-phone-to-pc'
    | '/how-to/send-pdf-phone-to-pc'
    | '/how-to/send-photos-phone-to-pc'
    | '/how-to/share-files-same-wifi'
    | '/s/$id'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/airdrop-alternative'
    | '/help'
    | '/join'
    | '/privacy'
    | '/video'
    | '/why-quickbridge'
    | '/compare/quickbridge-vs-airdrop'
    | '/compare/quickbridge-vs-pairdrop'
    | '/compare/quickbridge-vs-snapdrop'
    | '/compare/quickbridge-vs-wetransfer'
    | '/compare/quickbridge-vs-wormhole'
    | '/how-to/send-files-android-to-mac'
    | '/how-to/send-files-android-to-windows'
    | '/how-to/send-files-iphone-to-mac'
    | '/how-to/send-files-iphone-to-windows'
    | '/how-to/send-files-phone-to-pc-free'
    | '/how-to/send-files-windows-to-android'
    | '/how-to/send-files-windows-to-iphone'
    | '/how-to/send-files-without-whatsapp'
    | '/how-to/send-large-files-phone-to-pc'
    | '/how-to/send-pdf-phone-to-pc'
    | '/how-to/send-photos-phone-to-pc'
    | '/how-to/share-files-same-wifi'
    | '/s/$id'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirdropAlternativeRoute: typeof AirdropAlternativeRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  PrivacyRoute: typeof PrivacyRoute
  VideoRoute: typeof VideoRoute
  WhyQuickbridgeRoute: typeof WhyQuickbridgeRoute
  CompareQuickbridgeVsAirdropRoute: typeof CompareQuickbridgeVsAirdropRoute
  CompareQuickbridgeVsPairdropRoute: typeof CompareQuickbridgeVsPairdropRoute
  CompareQuickbridgeVsSnapdropRoute: typeof CompareQuickbridgeVsSnapdropRoute
  CompareQuickbridgeVsWetransferRoute: typeof CompareQuickbridgeVsWetransferRoute
  CompareQuickbridgeVsWormholeRoute: typeof CompareQuickbridgeVsWormholeRoute
  HowToSendFilesAndroidToMacRoute: typeof HowToSendFilesAndroidToMacRoute
  HowToSendFilesAndroidToWindowsRoute: typeof HowToSendFilesAndroidToWindowsRoute
  HowToSendFilesIphoneToMacRoute: typeof HowToSendFilesIphoneToMacRoute
  HowToSendFilesIphoneToWindowsRoute: typeof HowToSendFilesIphoneToWindowsRoute
  HowToSendFilesPhoneToPcFreeRoute: typeof HowToSendFilesPhoneToPcFreeRoute
  HowToSendFilesWindowsToAndroidRoute: typeof HowToSendFilesWindowsToAndroidRoute
  HowToSendFilesWindowsToIphoneRoute: typeof HowToSendFilesWindowsToIphoneRoute
  HowToSendFilesWithoutWhatsappRoute: typeof HowToSendFilesWithoutWhatsappRoute
  HowToSendLargeFilesPhoneToPcRoute: typeof HowToSendLargeFilesPhoneToPcRoute
  HowToSendPdfPhoneToPcRoute: typeof HowToSendPdfPhoneToPcRoute
  HowToSendPhotosPhoneToPcRoute: typeof HowToSendPhotosPhoneToPcRoute
  HowToShareFilesSameWifiRoute: typeof HowToShareFilesSameWifiRoute
  SIdRoute: typeof SIdRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-quickbridge': {
      id: '/why-quickbridge'
      path: '/why-quickbridge'
      fullPath: '/why-quickbridge'
      preLoaderRoute: typeof WhyQuickbridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airdrop-alternative': {
      id: '/airdrop-alternative'
      path: '/airdrop-alternative'
      fullPath: '/airdrop-alternative'
      preLoaderRoute: typeof AirdropAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/share-files-same-wifi': {
      id: '/how-to/share-files-same-wifi'
      path: '/how-to/share-files-same-wifi'
      fullPath: '/how-to/share-files-same-wifi'
      preLoaderRoute: typeof HowToShareFilesSameWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-photos-phone-to-pc': {
      id: '/how-to/send-photos-phone-to-pc'
      path: '/how-to/send-photos-phone-to-pc'
      fullPath: '/how-to/send-photos-phone-to-pc'
      preLoaderRoute: typeof HowToSendPhotosPhoneToPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-pdf-phone-to-pc': {
      id: '/how-to/send-pdf-phone-to-pc'
      path: '/how-to/send-pdf-phone-to-pc'
      fullPath: '/how-to/send-pdf-phone-to-pc'
      preLoaderRoute: typeof HowToSendPdfPhoneToPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-large-files-phone-to-pc': {
      id: '/how-to/send-large-files-phone-to-pc'
      path: '/how-to/send-large-files-phone-to-pc'
      fullPath: '/how-to/send-large-files-phone-to-pc'
      preLoaderRoute: typeof HowToSendLargeFilesPhoneToPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-without-whatsapp': {
      id: '/how-to/send-files-without-whatsapp'
      path: '/how-to/send-files-without-whatsapp'
      fullPath: '/how-to/send-files-without-whatsapp'
      preLoaderRoute: typeof HowToSendFilesWithoutWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-windows-to-iphone': {
      id: '/how-to/send-files-windows-to-iphone'
      path: '/how-to/send-files-windows-to-iphone'
      fullPath: '/how-to/send-files-windows-to-iphone'
      preLoaderRoute: typeof HowToSendFilesWindowsToIphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-windows-to-android': {
      id: '/how-to/send-files-windows-to-android'
      path: '/how-to/send-files-windows-to-android'
      fullPath: '/how-to/send-files-windows-to-android'
      preLoaderRoute: typeof HowToSendFilesWindowsToAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-phone-to-pc-free': {
      id: '/how-to/send-files-phone-to-pc-free'
      path: '/how-to/send-files-phone-to-pc-free'
      fullPath: '/how-to/send-files-phone-to-pc-free'
      preLoaderRoute: typeof HowToSendFilesPhoneToPcFreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-iphone-to-windows': {
      id: '/how-to/send-files-iphone-to-windows'
      path: '/how-to/send-files-iphone-to-windows'
      fullPath: '/how-to/send-files-iphone-to-windows'
      preLoaderRoute: typeof HowToSendFilesIphoneToWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-iphone-to-mac': {
      id: '/how-to/send-files-iphone-to-mac'
      path: '/how-to/send-files-iphone-to-mac'
      fullPath: '/how-to/send-files-iphone-to-mac'
      preLoaderRoute: typeof HowToSendFilesIphoneToMacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-android-to-windows': {
      id: '/how-to/send-files-android-to-windows'
      path: '/how-to/send-files-android-to-windows'
      fullPath: '/how-to/send-files-android-to-windows'
      preLoaderRoute: typeof HowToSendFilesAndroidToWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to/send-files-android-to-mac': {
      id: '/how-to/send-files-android-to-mac'
      path: '/how-to/send-files-android-to-mac'
      fullPath: '/how-to/send-files-android-to-mac'
      preLoaderRoute: typeof HowToSendFilesAndroidToMacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-wormhole': {
      id: '/compare/quickbridge-vs-wormhole'
      path: '/compare/quickbridge-vs-wormhole'
      fullPath: '/compare/quickbridge-vs-wormhole'
      preLoaderRoute: typeof CompareQuickbridgeVsWormholeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-wetransfer': {
      id: '/compare/quickbridge-vs-wetransfer'
      path: '/compare/quickbridge-vs-wetransfer'
      fullPath: '/compare/quickbridge-vs-wetransfer'
      preLoaderRoute: typeof CompareQuickbridgeVsWetransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-snapdrop': {
      id: '/compare/quickbridge-vs-snapdrop'
      path: '/compare/quickbridge-vs-snapdrop'
      fullPath: '/compare/quickbridge-vs-snapdrop'
      preLoaderRoute: typeof CompareQuickbridgeVsSnapdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-pairdrop': {
      id: '/compare/quickbridge-vs-pairdrop'
      path: '/compare/quickbridge-vs-pairdrop'
      fullPath: '/compare/quickbridge-vs-pairdrop'
      preLoaderRoute: typeof CompareQuickbridgeVsPairdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-airdrop': {
      id: '/compare/quickbridge-vs-airdrop'
      path: '/compare/quickbridge-vs-airdrop'
      fullPath: '/compare/quickbridge-vs-airdrop'
      preLoaderRoute: typeof CompareQuickbridgeVsAirdropRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirdropAlternativeRoute: AirdropAlternativeRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  PrivacyRoute: PrivacyRoute,
  VideoRoute: VideoRoute,
  WhyQuickbridgeRoute: WhyQuickbridgeRoute,
  CompareQuickbridgeVsAirdropRoute: CompareQuickbridgeVsAirdropRoute,
  CompareQuickbridgeVsPairdropRoute: CompareQuickbridgeVsPairdropRoute,
  CompareQuickbridgeVsSnapdropRoute: CompareQuickbridgeVsSnapdropRoute,
  CompareQuickbridgeVsWetransferRoute: CompareQuickbridgeVsWetransferRoute,
  CompareQuickbridgeVsWormholeRoute: CompareQuickbridgeVsWormholeRoute,
  HowToSendFilesAndroidToMacRoute: HowToSendFilesAndroidToMacRoute,
  HowToSendFilesAndroidToWindowsRoute: HowToSendFilesAndroidToWindowsRoute,
  HowToSendFilesIphoneToMacRoute: HowToSendFilesIphoneToMacRoute,
  HowToSendFilesIphoneToWindowsRoute: HowToSendFilesIphoneToWindowsRoute,
  HowToSendFilesPhoneToPcFreeRoute: HowToSendFilesPhoneToPcFreeRoute,
  HowToSendFilesWindowsToAndroidRoute: HowToSendFilesWindowsToAndroidRoute,
  HowToSendFilesWindowsToIphoneRoute: HowToSendFilesWindowsToIphoneRoute,
  HowToSendFilesWithoutWhatsappRoute: HowToSendFilesWithoutWhatsappRoute,
  HowToSendLargeFilesPhoneToPcRoute: HowToSendLargeFilesPhoneToPcRoute,
  HowToSendPdfPhoneToPcRoute: HowToSendPdfPhoneToPcRoute,
  HowToSendPhotosPhoneToPcRoute: HowToSendPhotosPhoneToPcRoute,
  HowToShareFilesSameWifiRoute: HowToShareFilesSameWifiRoute,
  SIdRoute: SIdRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
