/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyQuickbridgeRouteImport } from './routes/why-quickbridge'
import { Route as VideoRouteImport } from './routes/video'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AirdropAlternativeRouteImport } from './routes/airdrop-alternative'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as CompareQuickbridgeVsWormholeRouteImport } from './routes/compare.quickbridge-vs-wormhole'
import { Route as CompareQuickbridgeVsWetransferRouteImport } from './routes/compare.quickbridge-vs-wetransfer'
import { Route as CompareQuickbridgeVsSnapdropRouteImport } from './routes/compare.quickbridge-vs-snapdrop'
import { Route as CompareQuickbridgeVsPairdropRouteImport } from './routes/compare.quickbridge-vs-pairdrop'
import { Route as CompareQuickbridgeVsAirdropRouteImport } from './routes/compare.quickbridge-vs-airdrop'

const WhyQuickbridgeRoute = WhyQuickbridgeRouteImport.update({
  id: '/why-quickbridge',
  path: '/why-quickbridge',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AirdropAlternativeRoute = AirdropAlternativeRouteImport.update({
  id: '/airdrop-alternative',
  path: '/airdrop-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareQuickbridgeVsWormholeRoute =
  CompareQuickbridgeVsWormholeRouteImport.update({
    id: '/compare/quickbridge-vs-wormhole',
    path: '/compare/quickbridge-vs-wormhole',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsWetransferRoute =
  CompareQuickbridgeVsWetransferRouteImport.update({
    id: '/compare/quickbridge-vs-wetransfer',
    path: '/compare/quickbridge-vs-wetransfer',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsSnapdropRoute =
  CompareQuickbridgeVsSnapdropRouteImport.update({
    id: '/compare/quickbridge-vs-snapdrop',
    path: '/compare/quickbridge-vs-snapdrop',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsPairdropRoute =
  CompareQuickbridgeVsPairdropRouteImport.update({
    id: '/compare/quickbridge-vs-pairdrop',
    path: '/compare/quickbridge-vs-pairdrop',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareQuickbridgeVsAirdropRoute =
  CompareQuickbridgeVsAirdropRouteImport.update({
    id: '/compare/quickbridge-vs-airdrop',
    path: '/compare/quickbridge-vs-airdrop',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airdrop-alternative': typeof AirdropAlternativeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/video': typeof VideoRoute
  '/why-quickbridge': typeof WhyQuickbridgeRoute
  '/compare/quickbridge-vs-airdrop': typeof CompareQuickbridgeVsAirdropRoute
  '/compare/quickbridge-vs-pairdrop': typeof CompareQuickbridgeVsPairdropRoute
  '/compare/quickbridge-vs-snapdrop': typeof CompareQuickbridgeVsSnapdropRoute
  '/compare/quickbridge-vs-wetransfer': typeof CompareQuickbridgeVsWetransferRoute
  '/compare/quickbridge-vs-wormhole': typeof CompareQuickbridgeVsWormholeRoute
  '/s/$id': typeof SIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airdrop-alternative': typeof AirdropAlternativeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/video': typeof VideoRoute
  '/why-quickbridge': typeof WhyQuickbridgeRoute
  '/compare/quickbridge-vs-airdrop': typeof CompareQuickbridgeVsAirdropRoute
  '/compare/quickbridge-vs-pairdrop': typeof CompareQuickbridgeVsPairdropRoute
  '/compare/quickbridge-vs-snapdrop': typeof CompareQuickbridgeVsSnapdropRoute
  '/compare/quickbridge-vs-wetransfer': typeof CompareQuickbridgeVsWetransferRoute
  '/compare/quickbridge-vs-wormhole': typeof CompareQuickbridgeVsWormholeRoute
  '/s/$id': typeof SIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airdrop-alternative': typeof AirdropAlternativeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/video': typeof VideoRoute
  '/why-quickbridge': typeof WhyQuickbridgeRoute
  '/compare/quickbridge-vs-airdrop': typeof CompareQuickbridgeVsAirdropRoute
  '/compare/quickbridge-vs-pairdrop': typeof CompareQuickbridgeVsPairdropRoute
  '/compare/quickbridge-vs-snapdrop': typeof CompareQuickbridgeVsSnapdropRoute
  '/compare/quickbridge-vs-wetransfer': typeof CompareQuickbridgeVsWetransferRoute
  '/compare/quickbridge-vs-wormhole': typeof CompareQuickbridgeVsWormholeRoute
  '/s/$id': typeof SIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airdrop-alternative'
    | '/help'
    | '/join'
    | '/privacy'
    | '/video'
    | '/why-quickbridge'
    | '/compare/quickbridge-vs-airdrop'
    | '/compare/quickbridge-vs-pairdrop'
    | '/compare/quickbridge-vs-snapdrop'
    | '/compare/quickbridge-vs-wetransfer'
    | '/compare/quickbridge-vs-wormhole'
    | '/s/$id'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airdrop-alternative'
    | '/help'
    | '/join'
    | '/privacy'
    | '/video'
    | '/why-quickbridge'
    | '/compare/quickbridge-vs-airdrop'
    | '/compare/quickbridge-vs-pairdrop'
    | '/compare/quickbridge-vs-snapdrop'
    | '/compare/quickbridge-vs-wetransfer'
    | '/compare/quickbridge-vs-wormhole'
    | '/s/$id'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/airdrop-alternative'
    | '/help'
    | '/join'
    | '/privacy'
    | '/video'
    | '/why-quickbridge'
    | '/compare/quickbridge-vs-airdrop'
    | '/compare/quickbridge-vs-pairdrop'
    | '/compare/quickbridge-vs-snapdrop'
    | '/compare/quickbridge-vs-wetransfer'
    | '/compare/quickbridge-vs-wormhole'
    | '/s/$id'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirdropAlternativeRoute: typeof AirdropAlternativeRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  PrivacyRoute: typeof PrivacyRoute
  VideoRoute: typeof VideoRoute
  WhyQuickbridgeRoute: typeof WhyQuickbridgeRoute
  CompareQuickbridgeVsAirdropRoute: typeof CompareQuickbridgeVsAirdropRoute
  CompareQuickbridgeVsPairdropRoute: typeof CompareQuickbridgeVsPairdropRoute
  CompareQuickbridgeVsSnapdropRoute: typeof CompareQuickbridgeVsSnapdropRoute
  CompareQuickbridgeVsWetransferRoute: typeof CompareQuickbridgeVsWetransferRoute
  CompareQuickbridgeVsWormholeRoute: typeof CompareQuickbridgeVsWormholeRoute
  SIdRoute: typeof SIdRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-quickbridge': {
      id: '/why-quickbridge'
      path: '/why-quickbridge'
      fullPath: '/why-quickbridge'
      preLoaderRoute: typeof WhyQuickbridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airdrop-alternative': {
      id: '/airdrop-alternative'
      path: '/airdrop-alternative'
      fullPath: '/airdrop-alternative'
      preLoaderRoute: typeof AirdropAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-wormhole': {
      id: '/compare/quickbridge-vs-wormhole'
      path: '/compare/quickbridge-vs-wormhole'
      fullPath: '/compare/quickbridge-vs-wormhole'
      preLoaderRoute: typeof CompareQuickbridgeVsWormholeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-wetransfer': {
      id: '/compare/quickbridge-vs-wetransfer'
      path: '/compare/quickbridge-vs-wetransfer'
      fullPath: '/compare/quickbridge-vs-wetransfer'
      preLoaderRoute: typeof CompareQuickbridgeVsWetransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-snapdrop': {
      id: '/compare/quickbridge-vs-snapdrop'
      path: '/compare/quickbridge-vs-snapdrop'
      fullPath: '/compare/quickbridge-vs-snapdrop'
      preLoaderRoute: typeof CompareQuickbridgeVsSnapdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-pairdrop': {
      id: '/compare/quickbridge-vs-pairdrop'
      path: '/compare/quickbridge-vs-pairdrop'
      fullPath: '/compare/quickbridge-vs-pairdrop'
      preLoaderRoute: typeof CompareQuickbridgeVsPairdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/quickbridge-vs-airdrop': {
      id: '/compare/quickbridge-vs-airdrop'
      path: '/compare/quickbridge-vs-airdrop'
      fullPath: '/compare/quickbridge-vs-airdrop'
      preLoaderRoute: typeof CompareQuickbridgeVsAirdropRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirdropAlternativeRoute: AirdropAlternativeRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  PrivacyRoute: PrivacyRoute,
  VideoRoute: VideoRoute,
  WhyQuickbridgeRoute: WhyQuickbridgeRoute,
  CompareQuickbridgeVsAirdropRoute: CompareQuickbridgeVsAirdropRoute,
  CompareQuickbridgeVsPairdropRoute: CompareQuickbridgeVsPairdropRoute,
  CompareQuickbridgeVsSnapdropRoute: CompareQuickbridgeVsSnapdropRoute,
  CompareQuickbridgeVsWetransferRoute: CompareQuickbridgeVsWetransferRoute,
  CompareQuickbridgeVsWormholeRoute: CompareQuickbridgeVsWormholeRoute,
  SIdRoute: SIdRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
